# Generated by Django 3.1.2 on 2020-12-10 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notesmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', django_cryptography.fields.encrypt(models.TextField(max_length=50))),
                ('description', django_cryptography.fields.encrypt(models.TextField(max_length=500))),
                ('category', django_cryptography.fields.encrypt(models.TextField(max_length=20))),
                ('due_date', django_cryptography.fields.encrypt(models.DateField())),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
